NUM_ATTEMPTS_TIL_ERROR = 5
SCROLLBAR_SCREENSHOT_NAME = "scrollbarScreenshot.png"
BUTTON_DETECTION_SCREENSHOT_NAME = "buttonDetectionScreenshot.png"
BUTTON_DETECTION_SCREENSHOT_AREA = (190, 132, 1156 - 190, 600 - 132)